cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53c37
      expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: wd9824321
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: true
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true


